<?php
acf_add_local_field_group(array(
    'key' => 'group_5e54222fcbeb0',
    'title' => 'Address and members',
    'fields' => array(
        array(
            'key' => 'field_5e542251181a9',
            'label' => 'Address and contact',
            'name' => 'contact_address',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_5e542273181aa',
                    'label' => 'Title',
                    'name' => 'contact_address_title',
                    'type' => 'text',
                    'instructions' => 'Short section title (max 2-3 words)',
                    'required' => 1,
                    'default_value' => 'Info',
                    'maxlength' => 30,
                ),
                array(
                    'key' => 'field_5e542293181ab',
                    'label' => 'Name of organization',
                    'name' => 'contact_address_organization',
                    'type' => 'text',
                    'instructions' => 'Full name of organization',
                    'required' => 1,
                    'default_value' => 'Theme Development',
                    'maxlength' => 75,
                ),
                array(
                    'key' => 'field_5e5422af181ac',
                    'label' => 'Address',
                    'name' => 'contact_address_physical_location',
                    'type' => 'text',
                    'instructions' => 'Physical address of organization',
                    'required' => 1,
                    'default_value' => 'Address 20, Virovitica',
                    'maxlength' => 75,
                ),
                array(
                    'key' => 'field_5e5422df181ae',
                    'label' => 'Phone number',
                    'name' => 'contact_address_phone',
                    'type' => 'text',
                    'instructions' => 'Add phone number',
                    'default_value' => '+3851234567',
                    'maxlength' => 30,
                ),
            ),
        ),
        array(
            'key' => 'field_5e54231730d46',
            'label' => 'Team members',
            'name' => 'contact_members',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_5e54233930d47',
                    'label' => 'Title',
                    'name' => 'contact_members_title',
                    'type' => 'text',
                    'instructions' => 'Short section title (max 2-3 words)',
                    'required' => 1,
                    'default_value' => 'Team members',
                    'maxlength' => 30,
                ),
                array(
                    'key' => 'field_5e54235730d48',
                    'label' => 'Member 1',
                    'name' => 'contact_members_1',
                    'type' => 'text',
                    'instructions' => 'First and Last Name',
                    'required' => 1,
                    'default_value' => 'Robin Smith',
                    'maxlength' => 30,
                ),
                array(
                    'key' => 'field_5e54236b30d49',
                    'label' => 'Member 2',
                    'name' => 'contact_members_2',
                    'type' => 'text',
                    'instructions' => 'First and Last Name',
                    'required' => 1,
                    'default_value' => 'Larry Hops',
                    'maxlength' => 30,
                ),
                array(
                    'key' => 'field_5e54237f30d4a',
                    'label' => 'Member 3',
                    'name' => 'contact_members_3',
                    'type' => 'text',
                    'instructions' => 'First and Last Name',
                    'default_value' => 'Kelly Doyne',
                    'maxlength' => 30,
                ),
                array(
                    'key' => 'field_5e54238a30d4b',
                    'label' => 'Member 4',
                    'name' => 'contact_members_4',
                    'type' => 'text',
                    'instructions' => 'First and Last Name',
                    'default_value' => 'Samantha Wilson',
                    'maxlength' => 30,
                ),
                array(
                    'key' => 'field_5e54239b30d4c',
                    'label' => 'Member 5',
                    'name' => 'contact_members_5',
                    'type' => 'text',
                    'instructions' => 'First and Last Name',
                    'default_value' => 'Henry Hill',
                    'maxlength' => 30,
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-templates/contact.php',
            ),
        ),
    ),
    'menu_order' => 90,
    'hide_on_screen' => array(
        0  => 'permalink',
        1  => 'the_content',
        2  => 'excerpt',
        3  => 'discussion',
        4  => 'comments',
        5  => 'revisions',
        6  => 'slug',
        7  => 'author',
        8  => 'format',
        9  => 'featured_image',
        10 => 'categories',
        11 => 'tags',
        12 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => 'Edit (contact)',
));
