<?php
acf_add_local_field_group(array(
    'key' => 'group_5df151764f2c0',
    'title' => 'Team members',
    'fields' => array(
        array(
            'key' => 'field_5df15196206f4',
            'label' => 'Title',
            'name' => 'home_members_title',
            'type' => 'text',
            'instructions' => 'Short section title (max 2-3 words)',
            'required' => 1,
            'default_value' => 'Team members',
            'maxlength' => 30,
        ),
        array(
            'key' => 'field_5df64b35c5fd7',
            'label' => 'Member 1',
            'name' => 'home_members_1',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_5df64b52c5fd8',
                    'label' => 'Name',
                    'name' => 'home_members_1_name',
                    'type' => 'text',
                    'instructions' => 'First and Last Name',
                    'required' => 1,
                    'default_value' => 'Robin Smith',
                    'maxlength' => 25,
                ),
                array(
                    'key' => 'field_5df64b74c5fd9',
                    'label' => 'Type',
                    'name' => 'home_members_1_type',
                    'type' => 'text',
                    'instructions' => 'What\'s his role? (max 2-3 words)',
                    'required' => 1,
                    'default_value' => 'Tester',
                    'maxlength' => 35,
                ),
                array(
                    'key' => 'field_5df68579c137f',
                    'label' => 'Link',
                    'name' => 'home_members_1_link',
                    'type' => 'text',
                    'instructions' => 'URL of member page',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_5df64b9dc5fda',
                    'label' => 'Image',
                    'name' => 'home_members_1_image',
                    'type' => 'image',
                    'instructions' => 'Add member image (size <b>280x340px</b>)<br> note: all member\'s images should be the same size for design consistency',
                    'required' => 1,
                    'preview_size' => 'medium',
                    'max_size' => '1,5',
                    'mime_types' => 'jpg, jpeg, png',
                ),
            ),
        ),
        array(
            'key' => 'field_60a01a2d13a05',
            'label' => 'Member 2',
            'name' => 'home_members_2',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_60a01a2d13a06',
                    'label' => 'Name',
                    'name' => 'home_members_2_name',
                    'type' => 'text',
                    'instructions' => 'First and Last Name',
                    'required' => 1,
                    'default_value' => 'Larry Hops',
                    'maxlength' => 25,
                ),
                array(
                    'key' => 'field_60a01a2d13a07',
                    'label' => 'Type',
                    'name' => 'home_members_2_type',
                    'type' => 'text',
                    'instructions' => 'What\'s his role? (max 2-3 words)',
                    'required' => 1,
                    'default_value' => 'Developer',
                    'maxlength' => 35,
                ),
                array(
                    'key' => 'field_60a01a2d13a08',
                    'label' => 'Link',
                    'name' => 'home_members_2_link',
                    'type' => 'text',
                    'instructions' => 'URL of member page',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_60a01a2d13a09',
                    'label' => 'Image',
                    'name' => 'home_members_2_image',
                    'type' => 'image',
                    'instructions' => 'Add member image (size <b>280x340px</b>)<br> note: all member\'s images should be the same size for design consistency',
                    'required' => 1,
                    'preview_size' => 'medium',
                    'max_size' => '1,5',
                    'mime_types' => 'jpg, jpeg, png',
                ),
            ),
        ),
        array(
            'key' => 'field_60a01a5a13a0a',
            'label' => 'Member 3',
            'name' => 'home_members_3',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_60a01a5a13a0b',
                    'label' => 'Name',
                    'name' => 'home_members_3_name',
                    'type' => 'text',
                    'instructions' => 'First and Last Name',
                    'required' => 1,
                    'default_value' => 'Kelly Doyne',
                    'maxlength' => 25,
                ),
                array(
                    'key' => 'field_60a01a5a13a0c',
                    'label' => 'Type',
                    'name' => 'home_members_3_type',
                    'type' => 'text',
                    'instructions' => 'What\'s his role? (max 2-3 words)',
                    'required' => 1,
                    'default_value' => 'Designer',
                    'maxlength' => 35,
                ),
                array(
                    'key' => 'field_60a01a5a13a0d',
                    'label' => 'Link',
                    'name' => 'home_members_3_link',
                    'type' => 'text',
                    'instructions' => 'URL of member page',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_60a01a5a13a0e',
                    'label' => 'Image',
                    'name' => 'home_members_3_image',
                    'type' => 'image',
                    'instructions' => 'Add member image (size <b>280x340px</b>)<br> note: all member\'s images should be the same size for design consistency',
                    'required' => 1,
                    'preview_size' => 'medium',
                    'max_size' => '1,5',
                    'mime_types' => 'jpg, jpeg, png',
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 40,
    'hide_on_screen' => array(
        0  => 'permalink',
        1  => 'the_content',
        2  => 'excerpt',
        3  => 'discussion',
        4  => 'comments',
        5  => 'revisions',
        6  => 'slug',
        7  => 'author',
        8  => 'format',
        9  => 'featured_image',
        10 => 'categories',
        11 => 'tags',
        12 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => 'Edit (homepage)',
));
