<?php
acf_add_local_field_group(array(
    'key' => 'group_5defcafdb9d82',
    'title' => 'Pricing',
    'fields' => array(
        array(
            'key' => 'field_5df14e72cd899',
            'label' => 'Title',
            'name' => 'home_pricing_title',
            'type' => 'text',
            'instructions' => 'Short section title (max 2-3 riječi)',
            'required' => 1,
            'default_value' => 'Pricing',
            'maxlength' => 30,
        ),
        array(
            'key' => 'field_5df533a838eb9',
            'label' => 'Option 1',
            'name' => 'home_pricing_option_1',
            'type' => 'group',
            'instructions' => 'Add value for option',
            'required' => 1,
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_5df533a838eba',
                    'label' => 'Price',
                    'name' => 'home_pricing_option_1_price',
                    'type' => 'text',
                    'instructions' => 'Option price',
                    'required' => 1,
                    'default_value' => 20,
                    'maxlength' => 10,
                ),
                array(
                    'key' => 'field_5df533a838ebb',
                    'label' => 'Currency and/or period',
                    'name' => 'home_pricing_option_1_currency_period',
                    'type' => 'text',
                    'instructions' => 'Currency and/or period to which the price refers',
                    'required' => 1,
                    'default_value' => 'kn',
                    'maxlength' => 10,
                ),
                array(
                    'key' => 'field_5df533a838ebc',
                    'label' => 'Description',
                    'name' => 'home_pricing_option_1_description',
                    'type' => 'text',
                    'instructions' => 'Description (max 2-3-words)',
                    'required' => 1,
                    'default_value' => 'Daily',
                    'maxlength' => 30,
                ),
            ),
        ),
        array(
            'key' => 'field_5df531e80dee7',
            'label' => 'Option 2',
            'name' => 'home_pricing_option_2',
            'type' => 'group',
            'instructions' => 'Add value for option',
            'required' => 1,
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_5df531e80dee8',
                    'label' => 'Price',
                    'name' => 'home_pricing_option_2_price',
                    'type' => 'text',
                    'instructions' => 'Option price',
                    'required' => 1,
                    'default_value' => 100,
                    'maxlength' => 10,
                ),
                array(
                    'key' => 'field_5df531e80dee9',
                    'label' => 'Currency and/or period',
                    'name' => 'home_pricing_option_2_currency_period',
                    'type' => 'text',
                    'instructions' => 'Currency and/or period to which the price refers',
                    'required' => 1,
                    'default_value' => 'kn',
                    'maxlength' => 10,
                ),
                array(
                    'key' => 'field_5df531e80deea',
                    'label' => 'Description',
                    'name' => 'home_pricing_option_2_description',
                    'type' => 'text',
                    'instructions' => 'Description (max 2-3-words)',
                    'required' => 1,
                    'default_value' => 'Weekly',
                    'maxlength' => 30,
                ),
            ),
        ),
        array(
            'key' => 'field_5df530a747d94',
            'label' => 'Option 3',
            'name' => 'home_pricing_option_3',
            'type' => 'group',
            'instructions' => 'Add value for option',
            'required' => 1,
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_5df530c147d95',
                    'label' => 'Price',
                    'name' => 'home_pricing_option_3_price',
                    'type' => 'text',
                    'instructions' => 'Option price',
                    'required' => 1,
                    'default_value' => 300,
                    'maxlength' => 10,
                ),
                array(
                    'key' => 'field_5df530e147d96',
                    'label' => 'Currency and/or period',
                    'name' => 'home_pricing_option_3_currency_period',
                    'type' => 'text',
                    'instructions' => 'Currency and/or period to which the price refers',
                    'required' => 1,
                    'default_value' => 'kn',
                    'maxlength' => 10,
                ),
                array(
                    'key' => 'field_5df5311b47d97',
                    'label' => 'Description',
                    'name' => 'home_pricing_option_3_description',
                    'type' => 'text',
                    'instructions' => 'Description (max 2-3-words)',
                    'required' => 1,
                    'default_value' => 'Monthly',
                    'maxlength' => 30,
                ),
            ),
        ),
        array(
            'key' => 'field_5df52f1c666b6',
            'label' => 'Option 4',
            'name' => 'home_pricing_option_4',
            'type' => 'group',
            'instructions' => 'Add value for option',
            'required' => 0,
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_5df52f3c666b7',
                    'label' => 'Price',
                    'name' => 'home_pricing_option_4_price',
                    'type' => 'text',
                    'instructions' => 'Option price',
                    'required' => 0,
                    'default_value' => 800,
                    'maxlength' => 10,
                ),
                array(
                    'key' => 'field_5df52f62666b8',
                    'label' => 'Currency and/or period',
                    'name' => 'home_pricing_option_4_currency_period',
                    'type' => 'text',
                    'instructions' => 'Currency and/or period to which the price refers',
                    'required' => 0,
                    'default_value' => 'kn',
                    'maxlength' => 10,
                ),
                array(
                    'key' => 'field_5df52f8e666b9',
                    'label' => 'Description',
                    'name' => 'home_pricing_option_4_description',
                    'type' => 'text',
                    'instructions' => 'Description (max 2-3-words)',
                    'required' => 0,
                    'default_value' => 'Quartally',
                    'maxlength' => 30,
                ),
            ),
        ),
        array(
            'key' => 'field_5defd19b03709',
            'label' => 'Option 5',
            'name' => 'home_pricing_option_5',
            'type' => 'group',
            'instructions' => 'Add value for option',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_5df529c0208e0',
                    'label' => 'Price',
                    'name' => 'home_pricing_option_5_price',
                    'type' => 'text',
                    'instructions' => 'Option price',
                    'default_value' => '1000-1500',
                    'maxlength' => 10,
                ),
                array(
                    'key' => 'field_5df52c1d16792',
                    'label' => 'Currency and/or period',
                    'name' => 'home_pricing_option_5_currency_period',
                    'type' => 'text',
                    'instructions' => 'Currency and/or period to which the price refers',
                    'default_value' => 'kn',
                    'maxlength' => 10,
                ),
                array(
                    'key' => 'field_5df529ed208e1',
                    'label' => 'Description',
                    'name' => 'home_pricing_option_5_description',
                    'type' => 'text',
                    'instructions' => 'Description (max 2-3-words)',
                    'default_value' => 'Semi-annually',
                    'maxlength' => 30,
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 20,
    'hide_on_screen' => array(
        0  => 'permalink',
        1  => 'the_content',
        2  => 'excerpt',
        3  => 'discussion',
        4  => 'comments',
        5  => 'revisions',
        6  => 'slug',
        7  => 'author',
        8  => 'format',
        9  => 'featured_image',
        10 => 'categories',
        11 => 'tags',
        12 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => 'Edit (homepage)',
));
