<?php
acf_add_local_field_group(array(
    'key' => 'group_5defc60e9a4a3',
    'title' => 'Intro',
    'fields' => array(
        array(
            'key' => 'field_5defc71a5f278',
            'label' => 'Title',
            'name' => 'home_intro_title',
            'type' => 'text',
            'instructions' => 'Short section title (max 2-3 words)',
            'required' => 1,
            'default_value' => 'Who we are?',
            'maxlength' => 30,
        ),
        array(
            'key' => 'field_5defc7535f279',
            'label' => 'Description',
            'name' => 'home_intro_description',
            'type' => 'textarea',
            'instructions' => 'Short section description (2-3 sentence)',
            'required' => 1,
            'default_value' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.',
            'maxlength' => 1000,
            'rows' => 3,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_5df5363f71ca7',
            'label' => 'Icons',
            'name' => 'home_intro_icons',
            'type' => 'group',
            'instructions' => 'Add icons title',
            'required' => 1,
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_5df5366171ca8',
                    'label' => 'Icon 1',
                    'name' => 'home_intro_icons_1_title',
                    'type' => 'text',
                    'instructions' => 'Short icon title (max-2-3 words)',
                    'required' => 1,
                    'default_value' => 'eirmod tempor',
                    'maxlength' => 30,
                ),
                array(
                    'key' => 'field_5df536cd71ca9',
                    'label' => 'Icon 2',
                    'name' => 'home_intro_icons_2_title',
                    'type' => 'text',
                    'instructions' => 'Short icon title (max-2-3 words)',
                    'required' => 1,
                    'default_value' => 'dolore magna',
                    'maxlength' => 30,
                ),
                array(
                    'key' => 'field_5df536f571caa',
                    'label' => 'Icon 3',
                    'name' => 'home_intro_icons_3_title',
                    'type' => 'text',
                    'instructions' => 'Short icon title (max-2-3 words)',
                    'required' => 1,
                    'default_value' => 'nonumy eirmod',
                    'maxlength' => 30,
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 10,
    'hide_on_screen' => array(
        0  => 'permalink',
        1  => 'the_content',
        2  => 'excerpt',
        3  => 'discussion',
        4  => 'comments',
        5  => 'revisions',
        6  => 'slug',
        7  => 'author',
        8  => 'format',
        9  => 'featured_image',
        10 => 'categories',
        11 => 'tags',
        12 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => 'Edit (homepage)',
));
