<?php
acf_add_local_field_group(array(
    'key' => 'group_5e56be3fee825',
    'title' => 'Sponsors',
    'fields' => array(
        array(
            'key' => 'field_5e56be3ff0e55',
            'label' => 'Sponsor 1',
            'name' => 'about_sponsor_1',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_5e56be3ff1a85',
                    'label' => 'Image',
                    'name' => 'about_sponsor_1_image',
                    'type' => 'image',
                    'instructions' => 'Choose image (ideal size <b>240x170px</b>)',
                    'preview_size' => 'medium',
                    'mime_types' => 'jpg, jpeg, png',
                ),
                array(
                    'key' => 'field_5e56be3ff1abd',
                    'label' => 'Link',
                    'name' => 'about_sponsor_1_link',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_5f7751ca07e97',
                    'label' => 'Show',
                    'name' => 'about_sponsor_1_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_609ffb31fc214',
            'label' => 'Sponsor 2',
            'name' => 'about_sponsor_2',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_609ffb31fc215',
                    'label' => 'Image',
                    'name' => 'about_sponsor_2_image',
                    'type' => 'image',
                    'instructions' => 'Choose image (ideal size <b>240x170px</b>)',
                    'preview_size' => 'medium',
                    'mime_types' => 'jpg, jpeg, png',
                ),
                array(
                    'key' => 'field_609ffb31fc216',
                    'label' => 'Link',
                    'name' => 'about_sponsor_2_link',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_609ffb31fc217',
                    'label' => 'Show',
                    'name' => 'about_sponsor_2_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_609ffb58fc218',
            'label' => 'Sponsor 3',
            'name' => 'about_sponsor_3',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_609ffb58fc219',
                    'label' => 'Image',
                    'name' => 'about_sponsor_3_image',
                    'type' => 'image',
                    'instructions' => 'Choose image (ideal size <b>240x170px</b>)',
                    'preview_size' => 'medium',
                    'mime_types' => 'jpg, jpeg, png',
                ),
                array(
                    'key' => 'field_609ffb58fc21a',
                    'label' => 'Link',
                    'name' => 'about_sponsor_3_link',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_609ffb58fc21b',
                    'label' => 'Show',
                    'name' => 'about_sponsor_3_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_609ffb73fc21c',
            'label' => 'Sponsor 4',
            'name' => 'about_sponsor_4',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_609ffb73fc21d',
                    'label' => 'Image',
                    'name' => 'about_sponsor_4_image',
                    'type' => 'image',
                    'instructions' => 'Choose image (ideal size <b>240x170px</b>)',
                    'preview_size' => 'medium',
                    'mime_types' => 'jpg, jpeg, png',
                ),
                array(
                    'key' => 'field_609ffb73fc21e',
                    'label' => 'Link',
                    'name' => 'about_sponsor_4_link',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_609ffb73fc21f',
                    'label' => 'Show',
                    'name' => 'about_sponsor_4_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_609ffb92fc220',
            'label' => 'Sponsor 5',
            'name' => 'about_sponsor_5',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_609ffb92fc221',
                    'label' => 'Image',
                    'name' => 'about_sponsor_5_image',
                    'type' => 'image',
                    'instructions' => 'Choose image (ideal size <b>240x170px</b>)',
                    'preview_size' => 'medium',
                    'mime_types' => 'jpg, jpeg, png',
                ),
                array(
                    'key' => 'field_609ffb92fc222',
                    'label' => 'Link',
                    'name' => 'about_sponsor_5_link',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_609ffb92fc223',
                    'label' => 'Show',
                    'name' => 'about_sponsor_5_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_609ffba5fc224',
            'label' => 'Sponsor 6',
            'name' => 'about_sponsor_6',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_609ffba5fc225',
                    'label' => 'Image',
                    'name' => 'about_sponsor_6_image',
                    'type' => 'image',
                    'instructions' => 'Choose image (ideal size <b>240x170px</b>)',
                    'preview_size' => 'medium',
                    'mime_types' => 'jpg, jpeg, png',
                ),
                array(
                    'key' => 'field_609ffba5fc226',
                    'label' => 'Link',
                    'name' => 'about_sponsor_6_link',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_609ffba5fc227',
                    'label' => 'Show',
                    'name' => 'about_sponsor_6_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_609ffbb9fc228',
            'label' => 'Sponsor 7',
            'name' => 'about_sponsor_7',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_609ffbbafc229',
                    'label' => 'Image',
                    'name' => 'about_sponsor_7_image',
                    'type' => 'image',
                    'instructions' => 'Choose image (ideal size <b>240x170px</b>)',
                    'preview_size' => 'medium',
                    'mime_types' => 'jpg, jpeg, png',
                ),
                array(
                    'key' => 'field_609ffbbafc22a',
                    'label' => 'Link',
                    'name' => 'about_sponsor_7_link',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_609ffbbafc22b',
                    'label' => 'Show',
                    'name' => 'about_sponsor_7_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_609ffbcdfc22c',
            'label' => 'Sponsor 8',
            'name' => 'about_sponsor_8',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_609ffbcdfc22d',
                    'label' => 'Image',
                    'name' => 'about_sponsor_8_image',
                    'type' => 'image',
                    'instructions' => 'Choose image (ideal size <b>240x170px</b>)',
                    'preview_size' => 'medium',
                    'mime_types' => 'jpg, jpeg, png',
                ),
                array(
                    'key' => 'field_609ffbcdfc22e',
                    'label' => 'Link',
                    'name' => 'about_sponsor_8_link',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_609ffbcdfc22f',
                    'label' => 'Show',
                    'name' => 'about_sponsor_8_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_609ffbeffc230',
            'label' => 'Sponsor 9',
            'name' => 'about_sponsor_9',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_609ffbeffc231',
                    'label' => 'Image',
                    'name' => 'about_sponsor_9_image',
                    'type' => 'image',
                    'instructions' => 'Choose image (ideal size <b>240x170px</b>)',
                    'preview_size' => 'medium',
                    'mime_types' => 'jpg, jpeg, png',
                ),
                array(
                    'key' => 'field_609ffbeffc232',
                    'label' => 'Link',
                    'name' => 'about_sponsor_9_link',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_609ffbeffc233',
                    'label' => 'Show',
                    'name' => 'about_sponsor_9_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_609ffc0efc234',
            'label' => 'Sponsor 10',
            'name' => 'about_sponsor_10',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_609ffc0efc235',
                    'label' => 'Image',
                    'name' => 'about_sponsor_10_image',
                    'type' => 'image',
                    'instructions' => 'Choose image (ideal size <b>240x170px</b>)',
                    'preview_size' => 'medium',
                    'mime_types' => 'jpg, jpeg, png',
                ),
                array(
                    'key' => 'field_609ffc0efc236',
                    'label' => 'Link',
                    'name' => 'about_sponsor_10_link',
                    'type' => 'text',
                ),
                array(
                    'key' => 'field_609ffc0efc237',
                    'label' => 'Show',
                    'name' => 'about_sponsor_10_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-templates/about-us.php',
            ),
        ),
    ),
    'menu_order' => 150,
    'hide_on_screen' => array(
        0  => 'permalink',
        1  => 'the_content',
        2  => 'excerpt',
        3  => 'discussion',
        4  => 'comments',
        5  => 'revisions',
        6  => 'slug',
        7  => 'author',
        8  => 'format',
        9  => 'featured_image',
        10 => 'categories',
        11 => 'tags',
        12 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => 'Edit (about us)',
));
