<?php
acf_add_local_field_group(array(
    'key' => 'group_5e56b20f47888',
    'title' => 'Features',
    'fields' => array(
        array(
            'key' => 'field_5e56b31d01581',
            'label' => 'Title',
            'name' => 'about_features_title',
            'type' => 'text',
            'instructions' => 'Short section title (max 2-3 words)',
            'required' => 1,
            'default_value' => 'Why choose us',
            'maxlength' => 35,
        ),
        array(
            'key' => 'field_5e56b23a01580',
            'label' => 'Description',
            'name' => 'about_features_description',
            'type' => 'textarea',
            'instructions' => 'Short section description (2-3 sentence)',
            'required' => 1,
            'default_value' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.',
            'maxlength' => 600,
            'rows' => 5,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_5e56b4a0e84db',
            'label' => 'Cards',
            'name' => 'about_features_cards',
            'type' => 'group',
            'layout' => 'table',
            'sub_fields' => array(
                array(
                    'key' => 'field_5e56b4c0e84dc',
                    'label' => 'Card 1',
                    'name' => 'about_features_card_1',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5e56b4e7e84dd',
                            'label' => 'Number/label',
                            'name' => 'about_features_card_1_label',
                            'type' => 'text',
                            'required' => 1,
                            'default_value' => '30+',
                            'maxlength' => 25,
                        ),
                        array(
                            'key' => 'field_5e56b519e84de',
                            'label' => 'Description',
                            'name' => 'about_features_card_1_description',
                            'type' => 'text',
                            'required' => 1,
                            'default_value' => 'Awards',
                            'maxlength' => 25,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_5e56b5d52e85c',
                    'label' => 'Card 2',
                    'name' => 'about_features_card_2',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5e56b5d52e85d',
                            'label' => 'Number/label',
                            'name' => 'about_features_card_2_label',
                            'type' => 'text',
                            'required' => 1,
                            'default_value' => '45+',
                            'maxlength' => 25,
                        ),
                        array(
                            'key' => 'field_5e56b5d52e85e',
                            'label' => 'Description',
                            'name' => 'about_features_card_2_description',
                            'type' => 'text',
                            'required' => 1,
                            'default_value' => 'Industry experts',
                            'maxlength' => 25,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_5e56b5fb2e85f',
                    'label' => 'Card 3',
                    'name' => 'about_features_card_3',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5e56b5fb2e860',
                            'label' => 'Number/label',
                            'name' => 'about_features_card_3_label',
                            'type' => 'text',
                            'required' => 1,
                            'default_value' => '110+',
                            'maxlength' => 25,
                        ),
                        array(
                            'key' => 'field_5e56b5fb2e861',
                            'label' => 'Description',
                            'name' => 'about_features_card_3_description',
                            'type' => 'text',
                            'required' => 1,
                            'default_value' => 'Satisfied clients',
                            'maxlength' => 25,
                        ),
                    ),
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-templates/about-us.php',
            ),
        ),
    ),
    'menu_order' => 130,
    'hide_on_screen' => array(
        0  => 'permalink',
        1  => 'the_content',
        2  => 'excerpt',
        3  => 'discussion',
        4  => 'comments',
        5  => 'revisions',
        6  => 'slug',
        7  => 'author',
        8  => 'format',
        9  => 'featured_image',
        10 => 'categories',
        11 => 'tags',
        12 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => 'Edit (about us)',
));
