<?php
acf_add_local_field_group(array(
    'key' => 'group_5e56b040cecba',
    'title' => 'Intro',
    'fields' => array(
        array(
            'key' => 'field_5e56b06acce10',
            'label' => 'Title',
            'name' => 'about_intro_title',
            'type' => 'text',
            'instructions' => 'Short section title (max 2-3 words)',
            'required' => 1,
            'default_value' => 'Who we are',
            'maxlength' => 35,
        ),
        array(
            'key' => 'field_5e56b0cd244ea',
            'label' => 'Description',
            'name' => 'about_intro_description',
            'type' => 'textarea',
            'instructions' => 'Short section description (2-3 sentence)',
            'required' => 1,
            'default_value' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor amet. Lorem ipsum dolorit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est.',
            'maxlength' => 1100,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_5e56b167244eb',
            'label' => 'Image',
            'name' => 'about_intro_image',
            'type' => 'image',
            'instructions' => 'Add image (ideal size<b>550x470px</b>)',
            'required' => 1,
            'preview_size' => 'medium',
            'mime_types' => 'jpg, jpeg, png',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-templates/about-us.php',
            ),
        ),
    ),
    'menu_order' => 120,
    'hide_on_screen' => array(
        0  => 'permalink',
        1  => 'the_content',
        2  => 'excerpt',
        3  => 'discussion',
        4  => 'comments',
        5  => 'revisions',
        6  => 'slug',
        7  => 'author',
        8  => 'format',
        9  => 'featured_image',
        10 => 'categories',
        11 => 'tags',
        12 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => 'Edit (about us)',
));
