<?php
acf_add_local_field_group(array(
    'key' => 'group_607f0713654f4',
    'title' => 'Testimonials',
    'fields' => array(
        array(
            'key' => 'field_607f07140464e',
            'label' => 'Title',
            'name' => 'about_testimonials_title',
            'type' => 'text',
            'instructions' => 'Short section title (max 2-3 words)',
            'required' => 1,
            'default_value' => 'Testimonials',
            'maxlength' => 30,
        ),
        array(
            'key' => 'field_607f071404e1f',
            'label' => 'Comment 1',
            'name' => 'about_testimonials_comment_1',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_607f0714cb615',
                    'label' => 'Text',
                    'name' => 'about_testimonials_comment_1_text',
                    'type' => 'textarea',
                    'instructions' => 'Short client comment (2-3 sentences)',
                    'default_value' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata.',
                    'maxlength' => 390,
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_607f0714cb9fd',
                    'label' => 'Author',
                    'name' => 'about_testimonials_comment_1_author',
                    'type' => 'text',
                    'instructions' => 'Name of author',
                    'default_value' => 'John Hedge',
                    'maxlength' => 35,
                ),
                array(
                    'key' => 'field_607f0714cbde5',
                    'label' => 'Show',
                    'name' => 'about_testimonials_comment_1_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_607f071405207',
            'label' => 'Comment 2',
            'name' => 'about_testimonials_comment_2',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_607f071546d17',
                    'label' => 'Text',
                    'name' => 'about_testimonials_comment_2_text',
                    'type' => 'textarea',
                    'instructions' => 'Short client comment (2-3 sentences)',
                    'default_value' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctu. Invidunt ut labore et dolore magna aliquyam erat sed diam nonumy eirmod.',
                    'maxlength' => 390,
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_607f0715470ff',
                    'label' => 'Author',
                    'name' => 'about_testimonials_comment_2_author',
                    'type' => 'text',
                    'instructions' => 'Name of author',
                    'default_value' => 'Sally Garden',
                    'maxlength' => 35,
                ),
                array(
                    'key' => 'field_607f0715474e7',
                    'label' => 'Show',
                    'name' => 'about_testimonials_comment_2_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_607f0714059d7',
            'label' => 'Comment 3',
            'name' => 'about_testimonials_comment_3',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_607f071648c91',
                    'label' => 'Text',
                    'name' => 'about_testimonials_comment_3_text',
                    'type' => 'textarea',
                    'instructions' => 'Short client comment (2-3 sentences)',
                    'default_value' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanct. vero eos et accusam et justo duo dolores et ea rebum consetetur sadipscing elitr sed diam nonumy sea takimata sanct.',
                    'maxlength' => 390,
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_607f071649079',
                    'label' => 'Author',
                    'name' => 'about_testimonials_comment_3_author',
                    'type' => 'text',
                    'instructions' => 'Name of author',
                    'default_value' => 'Ryen Anderson',
                    'maxlength' => 35,
                ),
                array(
                    'key' => 'field_607f071649461',
                    'label' => 'Show',
                    'name' => 'about_testimonials_comment_3_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_607f071406977',
            'label' => 'Comment 4',
            'name' => 'about_testimonials_comment_4',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_607f0716bb89c',
                    'label' => 'Text',
                    'name' => 'about_testimonials_comment_4_text',
                    'type' => 'textarea',
                    'instructions' => 'Short client comment (2-3 sentences)',
                    'default_value' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanct.',
                    'maxlength' => 390,
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_607f0716bbc84',
                    'label' => 'Author',
                    'name' => 'about_testimonials_comment_4_author',
                    'type' => 'text',
                    'instructions' => 'Name of author',
                    'default_value' => 'Firstname Lastname',
                    'maxlength' => 35,
                ),
                array(
                    'key' => 'field_607f0716bc06c',
                    'label' => 'Show',
                    'name' => 'about_testimonials_comment_4_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_607f071406d5f',
            'label' => 'Comment 5',
            'name' => 'about_testimonials_comment_5',
            'type' => 'group',
            'layout' => 'row',
            'sub_fields' => array(
                array(
                    'key' => 'field_607f071725e2a',
                    'label' => 'Text',
                    'name' => 'about_testimonials_comment_5_text',
                    'type' => 'textarea',
                    'instructions' => 'Short client comment (2-3 sentences)',
                    'default_value' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanct.',
                    'maxlength' => 390,
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_607f071726212',
                    'label' => 'Author',
                    'name' => 'about_testimonials_comment_5_author',
                    'type' => 'text',
                    'instructions' => 'Name of author',
                    'default_value' => 'Firstname Lastname',
                    'maxlength' => 35,
                ),
                array(
                    'key' => 'field_607f0717265fa',
                    'label' => 'Show',
                    'name' => 'about_testimonials_comment_5_checkbox',
                    'type' => 'checkbox',
                    'choices' => array(
                        '<b>Show</b>' => '<b>Show</b>',
                    ),
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'page-templates/about-us.php',
            ),
        ),
    ),
    'menu_order' => 140,
    'hide_on_screen' => array(
        0  => 'permalink',
        1  => 'the_content',
        2  => 'excerpt',
        3  => 'discussion',
        4  => 'comments',
        5  => 'revisions',
        6  => 'slug',
        7  => 'author',
        8  => 'format',
        9  => 'featured_image',
        10 => 'categories',
        11 => 'tags',
        12 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => 'Edit (about us)',
));
